AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  carp-connect

  SAM Template for carp-connect

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref UsersTable
        S3_BUCKET: !Ref FilesBucket
        COGNITO_USER_POOL_ID: !Ref UserPool
    VpcConfig:
      SubnetIds:
        - !ImportValue subnet-a
        - !ImportValue subnet-b
      SecurityGroupIds:
        - !ImportValue default-sg

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/carp-connect-api/
      Handler: lambda_handler.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: GET

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicitly created IAM Role for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn